spring:
  application:
    name: pragmatic-testing
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:derby:build/inmemorydb;create=true


pokemon:
  home: http://localhost:10000